=== jkr11/MolSim/input/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <!-- metadata (optional) -->
                <xs:element name="metadata" type="MetadataType"/>
                <!-- cuboids (n) -->
                <xs:element name="cuboids" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cuboid" type="cuboidType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- spheroids (n) -->
                <xs:element name="spheroids" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="spheroid" type="spheroidType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="MetadataType">
        <xs:sequence>
            <xs:element name="container" type="ContainerType"/>
            <xs:element name="force" type="ForceType"/>
            <xs:element name="delta_t" type="xs:decimal"/>
            <xs:element name="t_end" type="xs:double"/>
            <xs:element name="twoD" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cuboidType">
        <xs:sequence>
            <xs:element name="velocity" type="Dvec3Type"/>
            <xs:element name="corner" type="Dvec3Type"/>
            <xs:element name="dimensions" type="Ivec3Type"/>
            <xs:element name="type" type="xs:int"/>
            <xs:element name="h" type="xs:decimal"/>
            <xs:element name="mass" type="xs:decimal"/>
            <xs:element name="epsilon" type="xs:decimal"/>
            <xs:element name="sigma" type="xs:decimal"/>
            <xs:element name="mv" type="xs:decimal"/>
            <!--<xs:element name="twoD" type="xs:boolean" default="true"/>-->
        </xs:sequence>
    </xs:complexType>

    <!-- Spheroid Type -->
    <xs:complexType name="spheroidType">
        <xs:sequence>
            <xs:element name="velocity" type="Dvec3Type"/>
            <xs:element name="origin" type="Dvec3Type"/>
            <xs:element name="radius" type="xs:int"/>
            <xs:element name="type" type="xs:int"/>
            <xs:element name="h" type="xs:decimal"/>
            <xs:element name="mass" type="xs:decimal"/>
            <xs:element name="epsilon" type="xs:decimal"/>
            <xs:element name="sigma" type="xs:decimal"/>
            <!--<xs:element name="twoD" type="xs:boolean" default="true"/>-->
        </xs:sequence>
    </xs:complexType>

    <!-- VectorType for dvec3-->
    <xs:complexType name="Dvec3Type">
        <xs:sequence>
            <xs:element name="x" type="xs:decimal"/>
            <xs:element name="y" type="xs:decimal"/>
            <xs:element name="z" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    <!-- VectorType for dimension, std::array<int,3> -->
    <xs:complexType name="Ivec3Type">
        <xs:sequence>
            <xs:element name="x" type="xs:int"/>
            <xs:element name="y" type="xs:int"/>
            <xs:element name="z" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContainerType">
        <xs:choice>
            <xs:element name="directSum" type="DirectSumType"/>
            <xs:element name="linkedCells" type="LinkedCellsType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="LinkedCellsType">
        <xs:sequence>
            <xs:element name="domain" type="Ivec3Type"/>
            <xs:element name="r_cutoff" type="xs:decimal"/>
            <xs:element name="boundary" type="BoundaryConfigType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DirectSumType">
    </xs:complexType>

    <xs:complexType name="BoundaryType">
        <xs:choice>
            <xs:element name="Outflow"/>
            <xs:element name="Reflective"/>
            <xs:element name="Periodic"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="BoundaryConfigType">
        <xs:sequence>
            <xs:element name="x_high" type="BoundaryType"/>
            <xs:element name="x_low" type="BoundaryType"/>
            <xs:element name="y_high" type="BoundaryType"/>
            <xs:element name="y_low" type="BoundaryType"/>
            <xs:element name="z_high" type="BoundaryType"/>
            <xs:element name="z_low" type="BoundaryType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ForceType">
        <xs:choice>
            <xs:element name="Gravity"/>
            <xs:element name="LennardJones"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== jkr11/MolSim/input/week42.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>63</x>
                    <y>36</y>
                    <z>1</z>
                </domain>
                <r_cutoff>2.5</r_cutoff>
                <boundary>
                    <x_high>
                        <Reflective/>
                    </x_high>
                    <x_low>
                        <Reflective/>
                    </x_low>
                    <y_high>
                        <Reflective/>
                    </y_high>
                    <y_low>
                        <Reflective/>
                    </y_low>
                    <z_high>
                        <Outflow/>
                    </z_high>
                    <z_low>
                        <Outflow/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
            <SingularGravity g="-12.44"/>
        </force>
        <delta_t>0.0005</delta_t>
        <t_end>25</t_end>
        <twoD>true</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.6</x>
                <y>2</y>
                <z>0</z>
            </corner>
            <dimensions>
                <x>50</x>
                <y>14</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>1.2</h>
            <mass>1.0</mass>
            <epsilon>1.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.1</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <corner>
                <x>0.6</x>
                <y>19</y>
                <z>0</z>
            </corner>
            <dimensions>
                <x>50</x>
                <y>14</y>
                <z>1</z>
            </dimensions>
            <type>2</type>
            <h>1.2</h>
            <mass>2.0</mass>
            <epsilon>1.0</epsilon>
            <sigma>0.9412</sigma>
            <mv>0.1</mv>
        </cuboid>
    </cuboids>

</simulation>

=== jkr11/MolSim/input/week51.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>148</x>
                    <y>148</y>
                    <z>148</z>
                </domain>
                <r_cutoff>4.0</r_cutoff>
                <boundary>
                    <x_high>
                        <Outflow/>
                    </x_high>
                    <x_low>
                        <Outflow/>
                    </x_low>
                    <y_high>
                        <Outflow/>
                    </y_high>
                    <y_low>
                        <Outflow/>
                    </y_low>
                    <z_high>
                        <Reflective/>
                    </z_high>
                    <z_low>
                        <Reflective/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
            <HarmonicForce>
                <r_0>2.2</r_0>
                <k>300</k>
            </HarmonicForce>
            <IndexForce>
                <index>
                    <x>14</x>
                    <y>14</y>
                    <z>1</z>
                </index>
                <time>50</time>
                <force_values>
                    <x>1</x>
                    <y>1</y>
                    <z>1</z>
                </force_values>
            </IndexForce>
        </force>
        <delta_t>0.01</delta_t>
        <t_end>500</t_end>
        <twoD>false</twoD>
    </metadata>
    <membranes>
        <membrane>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <corner>
                <x>15</x>
                <y>15</y>
                <z>1.5</z>
            </corner>
            <dimensions>
                <x>50</x>
                <y>50</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>2.2</h>
            <mass>1.0</mass>
            <epsilon>1.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.0</mv>
        </membrane>
    </membranes>
</simulation>

=== jkr11/MolSim/tests/test_cuboid_gradual.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../input/input.xsd">
    <metadata>
        <container>
            <directSum/>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.015</delta_t>
        <t_end>15</t_end>
        <twoD>true</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </corner>
            <dimensions>
                <x>10</x>
                <y>2</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>1.1225</h>
            <mass>5.0</mass>
            <epsilon>0.1</epsilon>
            <sigma>0.2</sigma>
            <mv>0.0</mv>
        </cuboid>
    </cuboids>
    <thermostat>
        <T_init>1.0</T_init>
        <n_thermostat>100</n_thermostat>
        <T_target>10.0</T_target>
        <deltaT>2.0</deltaT>
    </thermostat>
</simulation>

=== jkr11/MolSim/input/week43.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>303</x>
                    <y>180</y>
                    <z>1</z>
                </domain>
                <r_cutoff>3.0</r_cutoff>
                <boundary>
                    <x_high>
                        <Reflective/>
                    </x_high>
                    <x_low>
                        <Reflective/>
                    </x_low>
                    <y_high>
                        <Reflective/>
                    </y_high>
                    <y_low>
                        <Reflective/>
                    </y_low>
                    <z_high>
                        <Outflow/>
                    </z_high>
                    <z_low>
                        <Outflow/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
            <SingularGravity g="-12.44"/>
        </force>
        <delta_t>0.0005</delta_t>
        <t_end>15</t_end>
        <twoD>true</twoD>
        <checkpoint>../scripts/output/test.xml</checkpoint>
    </metadata>
    <spheroids>
        <spheroid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <origin>
                <x>150</x>
                <y>150</y>
                <z>0</z>
            </origin>
            <radius>20</radius>
            <type>2</type>
            <h>1.2</h>
            <mass>1.0</mass>
            <epsilon>1.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.0</mv>
        </spheroid>
    </spheroids>
</simulation>

=== jkr11/MolSim/input/example_collision_3d.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <!-- THIS DOES NOT WORK YET -->
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>500</x>
                    <y>500</y>
                    <z>500</z>
                </domain>
                <r_cutoff>8.5</r_cutoff>
                <boundary>
                    <north>
                        <Reflective/>
                    </north>
                    <south>
                        <Reflective/>
                    </south>
                    <east>
                        <Reflective/>
                    </east>
                    <west>
                        <Reflective/>
                    </west>
                    <up>
                        <Reflective/>
                    </up>
                    <down>
                        <Reflective/>
                    </down>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.001</delta_t>
        <t_end>20</t_end>
        <twoD>false</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>20</x>
                <y>20</y>
                <z>20</z>
            </corner>
            <dimensions>
                <x>30</x>
                <y>30</y>
                <z>15</z>
            </dimensions>
            <type>1</type>
            <h>1.1225</h>
            <mass>100</mass>
            <epsilon>120</epsilon>
            <sigma>3.4</sigma>
            <mv>0</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>20.4</z>
            </velocity>
            <corner>
                <x>30</x>
                <y>30</y>
                <z>10</z>
            </corner>
            <dimensions>
                <x>10</x>
                <y>10</y>
                <z>10</z>
            </dimensions>
            <type>2</type>
            <h>1.1225</h>
            <mass>100</mass>
            <epsilon>120</epsilon>
            <sigma>3.4</sigma>
            <mv>0</mv>
        </cuboid>
    </cuboids>

</simulation>

=== jkr11/MolSim/input/task53big.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>60</x>
                    <y>60</y>
                    <z>60</z>
                </domain>
                <r_cutoff>3.6</r_cutoff>
                <boundary>
                    <x_high>
                        <Outflow></Outflow>
                    </x_high>
                    <x_low>
                        <Outflow></Outflow>
                    </x_low>
                    <y_high>
                        <Outflow></Outflow>
                    </y_high>
                    <y_low>
                        <Outflow></Outflow>
                    </y_low>
                    <z_high>
                        <Periodic></Periodic>
                    </z_high>
                    <z_low>
                        <Periodic></Periodic>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
            <SingularGravity>
                <g>-12.44</g>
                <axis>1</axis>
            </SingularGravity>
        </force>
        <delta_t>0.0005</delta_t>
        <t_end>100</t_end>
        <twoD>false</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <corner>
                <x>0.6</x>
                <y>0.6</y>
                <z>0.6</z>
            </corner>
            <dimensions>
                <x>50</x>
                <y>20</y>
                <z>50</z>
            </dimensions>
            <type>1</type>
            <h>1.2</h>
            <mass>1</mass>
            <epsilon>1</epsilon>
            <sigma>1.2</sigma>
            <mv>0</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <corner>
                <x>0.6</x>
                <y>24.6</y>
                <z>0.6</z>
            </corner>
            <dimensions>
                <x>50</x>
                <y>20</y>
                <z>50</z>
            </dimensions>
            <type>2</type>
            <h>1.2</h>
            <mass>1</mass>
            <epsilon>1</epsilon>
            <sigma>1.1</sigma>
            <mv>0.0</mv>
        </cuboid>
    </cuboids>
    <thermostat>
        <T_init>40</T_init>
        <n_thermostat>1000</n_thermostat>
    </thermostat>
</simulation>

=== jkr11/MolSim/tests/checkpoint_output_membrane_test.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/io/file/in/xml/input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>300</x>
                    <y>300</y>
                    <z>1</z>
                </domain>
                <r_cutoff>3.0</r_cutoff>
                <boundary>
                    <x_high>
                        <Outflow/>
                    </x_high>
                    <x_low>
                        <Outflow/>
                    </x_low>
                    <y_high>
                        <Outflow/>
                    </y_high>
                    <y_low>
                        <Outflow/>
                    </y_low>
                    <z_high>
                        <Outflow/>
                    </z_high>
                    <z_low>
                        <Outflow/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.0005</delta_t>
        <t_end>0</t_end>
        <twoD>true</twoD>
        <checkpoint>
            <name>../../input/checkpoint_membrane_test.xml</name>
            <is_membrane>true</is_membrane>
            <domain>
                <x>50</x>
                <y>50</y>
                <z>1</z>
            </domain>
        </checkpoint>
    </metadata>
</simulation>
