=== jkr11/MolSim/input/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="simulation">
        <xs:complexType>
            <xs:sequence>
                <!-- metadata (optional) -->
                <xs:element name="metadata" type="MetadataType"/>
                <!-- cuboids (n) -->
                <xs:element name="cuboids" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cuboid" type="cuboidType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- spheroids (n) -->
                <xs:element name="spheroids" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="spheroid" type="spheroidType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="MetadataType">
        <xs:sequence>
            <xs:element name="container" type="ContainerType"/>
            <xs:element name="force" type="ForceType"/>
            <xs:element name="delta_t" type="xs:decimal"/>
            <xs:element name="t_end" type="xs:double"/>
            <xs:element name="twoD" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cuboidType">
        <xs:sequence>
            <xs:element name="velocity" type="Dvec3Type"/>
            <xs:element name="corner" type="Dvec3Type"/>
            <xs:element name="dimensions" type="Ivec3Type"/>
            <xs:element name="type" type="xs:int"/>
            <xs:element name="h" type="xs:decimal"/>
            <xs:element name="mass" type="xs:decimal"/>
            <xs:element name="epsilon" type="xs:decimal"/>
            <xs:element name="sigma" type="xs:decimal"/>
            <xs:element name="mv" type="xs:decimal"/>
            <!--<xs:element name="twoD" type="xs:boolean" default="true"/>-->
        </xs:sequence>
    </xs:complexType>

    <!-- Spheroid Type -->
    <xs:complexType name="spheroidType">
        <xs:sequence>
            <xs:element name="velocity" type="Dvec3Type"/>
            <xs:element name="origin" type="Dvec3Type"/>
            <xs:element name="radius" type="xs:int"/>
            <xs:element name="type" type="xs:int"/>
            <xs:element name="h" type="xs:decimal"/>
            <xs:element name="mass" type="xs:decimal"/>
            <xs:element name="epsilon" type="xs:decimal"/>
            <xs:element name="sigma" type="xs:decimal"/>
            <!--<xs:element name="twoD" type="xs:boolean" default="true"/>-->
        </xs:sequence>
    </xs:complexType>

    <!-- VectorType for dvec3-->
    <xs:complexType name="Dvec3Type">
        <xs:sequence>
            <xs:element name="x" type="xs:decimal"/>
            <xs:element name="y" type="xs:decimal"/>
            <xs:element name="z" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
    <!-- VectorType for dimension, std::array<int,3> -->
    <xs:complexType name="Ivec3Type">
        <xs:sequence>
            <xs:element name="x" type="xs:int"/>
            <xs:element name="y" type="xs:int"/>
            <xs:element name="z" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContainerType">
        <xs:choice>
            <xs:element name="directSum" type="DirectSumType"/>
            <xs:element name="linkedCells" type="LinkedCellsType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="LinkedCellsType">
        <xs:sequence>
            <xs:element name="domain" type="Ivec3Type"/>
            <xs:element name="r_cutoff" type="xs:decimal"/>
            <xs:element name="boundary" type="BoundaryConfigType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DirectSumType">
    </xs:complexType>

    <xs:complexType name="BoundaryType">
        <xs:choice>
            <xs:element name="Outflow"/>
            <xs:element name="Reflective"/>
            <xs:element name="Periodic"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="BoundaryConfigType">
        <xs:sequence>
            <xs:element name="x_high" type="BoundaryType"/>
            <xs:element name="x_low" type="BoundaryType"/>
            <xs:element name="y_high" type="BoundaryType"/>
            <xs:element name="y_low" type="BoundaryType"/>
            <xs:element name="z_high" type="BoundaryType"/>
            <xs:element name="z_low" type="BoundaryType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ForceType">
        <xs:choice>
            <xs:element name="Gravity"/>
            <xs:element name="LennardJones"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== jkr11/MolSim/input/eingabe-sonne.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <directSum/>
        </container>
        <force>
            <Gravity/>
        </force>
        <delta_t>0.014</delta_t>
        <t_end>10</t_end>
        <twoD>true</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>0.0</h>
            <mass>1.0</mass>
            <epsilon>0.0</epsilon>
            <sigma>0.0</sigma>
            <mv>0.0</mv>
            <!--<twoD>false</twoD>-->
        </cuboid>
        <cuboid>
            <velocity>
                <x>-1.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>1.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </dimensions>
            <type>2</type>
            <h>0.0</h>
            <mass>0.000003</mass>
            <epsilon>0.0</epsilon>
            <sigma>0.0</sigma>
            <mv>0.0</mv>
            <!--<twoD>false</twoD>-->
        </cuboid>
        <cuboid>
            <velocity>
                <x>-0.425</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>5.36</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </dimensions>
            <type>3</type>
            <h>0.0</h>
            <mass>0.000955</mass>
            <epsilon>0.0</epsilon>
            <sigma>0.0</sigma>
            <mv>0.0</mv>
            <!--<twoD>false</twoD>-->
        </cuboid>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0296</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>34.75</x>
                <y>0.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </dimensions>
            <type>4</type>
            <h>0.0</h>
            <mass>0.00000000000001</mass>
            <epsilon>0.0</epsilon>
            <sigma>0.0</sigma>
            <mv>0.0</mv>
            <!--<twoD>false</twoD>-->
        </cuboid>
    </cuboids>
</simulation>

=== jkr11/MolSim/input/test_cuboid_spheroid.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>400</x>
                    <y>400</y>
                    <z>1</z>
                </domain>
                <r_cutoff>3.0</r_cutoff>
                <boundary>
                    <x_high>
                        <Outflow/>
                    </x_high>
                    <x_low>
                        <Outflow/>
                    </x_low>
                    <y_high>
                        <Outflow/>
                    </y_high>
                    <y_low>
                        <Outflow/>
                    </y_low>
                    <z_high>
                        <Outflow/>
                    </z_high>
                    <z_low>
                        <Outflow/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.015</delta_t>
        <t_end>15</t_end>
        <twoD>false</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>10</x>
                <y>10</y>
                <z>10</z>
            </dimensions>
            <type>1</type>
            <h>1.1225</h>
            <mass>5.0</mass>
            <epsilon>0.1</epsilon>
            <sigma>0.2</sigma>
            <mv>0.3</mv>
        </cuboid>
    </cuboids>
    <spheroids>
        <spheroid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <origin>
                <x>15.0</x>
                <y>15.0</y>
                <z>15.0</z>
            </origin>
            <radius>5</radius>
            <type>2</type>
            <h>1.1225</h>
            <mass>3.0</mass>
            <epsilon>5</epsilon>
            <sigma>1</sigma>
            <mv>0.1</mv>
        </spheroid>
    </spheroids>
</simulation>

=== jkr11/MolSim/input/week24LC.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>290</x>
                    <y>290</y>
                    <z>200</z>
                </domain>
                <r_cutoff>3.0</r_cutoff>
                <boundary>
                    <Boundary/>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.0002</delta_t>
        <t_end>5</t_end>
        <twoD>true</twoD>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>40</x>
                <y>8</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>1.1225</h>
            <mass>1.0</mass>
            <epsilon>5.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.1</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>-10.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>15</x>
                <y>15</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>8</x>
                <y>8</y>
                <z>1</z>
            </dimensions>
            <type>2</type>
            <h>1.1225</h>
            <mass>1.0</mass>
            <epsilon>5.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.1</mv>
        </cuboid>
    </cuboids>

</simulation>

=== jkr11/MolSim/input/week34.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata delta_t="0.00005" t_end="10" r_cutoff="3.0">
        <domain>
            <x>120</x>
            <y>50</y>
            <z>1</z>
        </domain>
    </metadata>
    <spheroids>
        <spheroid>
            <velocity>
                <x>0.0</x>
                <y>-10</y>
                <z>0.0</z>
            </velocity>
            <origin>
                <x>60</x>
                <y>25</y>
                <z>0</z>
            </origin>
            <radius>15</radius>
            <type>2</type>
            <h>1.1225</h>
            <mass>1.0</mass>
            <epsilon>5</epsilon>
            <sigma>1</sigma>
            <twoD>true</twoD>
        </spheroid>
    </spheroids>
</simulation>

=== jkr11/MolSim/input/testcuboid.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../src/io/file/in/input.xsd">

    <!-- Cuboids section with multiple cuboid entries -->
    <cuboids>
        <cuboid>
            <velocity>
                <x>1.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </corner>
            <dimensions>
                <x>10</x>
                <y>10</y>
                <z>10</z>
            </dimensions>
            <type>1</type>
            <h>0.5</h>
            <mass>100.0</mass>
            <epsilon>0.8</epsilon>
            <sigma>0.5</sigma>
            <mv>1.5</mv>
        </cuboid>

        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>1.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>5.0</x>
                <y>5.0</y>
                <z>5.0</z>
            </corner>
            <dimensions>
                <x>15</x>
                <y>10</y>
                <z>10</z>
            </dimensions>
            <type>2</type>
            <h>0.6</h>
            <mass>200.0</mass>
            <epsilon>0.9</epsilon>
            <sigma>0.7</sigma>
            <mv>2.0</mv>
        </cuboid>
    </cuboids>

</simulation>

=== jkr11/MolSim/input/week34_no_mv.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>120</x>
                    <y>50</y>
                    <z>1</z>
                </domain>
                <r_cutoff>3.0</r_cutoff>
                <boundary>
                    <x_high>
                        <Reflective/>
                    </x_high>
                    <x_low>
                        <Reflective/>
                    </x_low>
                    <y_high>
                        <Reflective/>
                    </y_high>
                    <y_low>
                        <Reflective/>
                    </y_low>
                    <z_high>
                        <Outflow/>
                    </z_high>
                    <z_low>
                        <Outflow/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
        </force>
        <delta_t>0.00005</delta_t>
        <t_end>10</t_end>
        <twoD>true</twoD>
    </metadata>
    <spheroids>
        <spheroid>
            <velocity>
                <x>0.0</x>
                <y>-10</y>
                <z>0.0</z>
            </velocity>
            <origin>
                <x>60</x>
                <y>25</y>
                <z>0</z>
            </origin>
            <radius>15</radius>
            <type>2</type>
            <h>1.1225</h>
            <mass>1.0</mass>
            <epsilon>5</epsilon>
            <sigma>1</sigma>
            <mv>0.0</mv>
        </spheroid>
    </spheroids>
</simulation>

=== jkr11/MolSim/input/task32_2k.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata delta_t="0.0005" t_end="20" r_cutoff="3.0">
        <domain>
            <x>100</x>
            <y>100</y>
            <z>10</z>
        </domain>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>1</x>
                <y>1</y>
                <z>1</z>
            </corner>
            <dimensions>
                <x>46</x>
                <y>46</y>
                <z>1</z>
            </dimensions>
            <type>1</type>
            <h>1.1225</h>
            <mass>1.0</mass>
            <epsilon>5.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.1</mv>
            <twoD>true</twoD>
        </cuboid>
    </cuboids>
</simulation>

=== jkr11/MolSim/input/week54_small_profiling.xml
<?xml version="1.0"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="input.xsd">
    <metadata>
        <container>
            <linkedCells>
                <domain>
                    <x>30</x>
                    <y>30</y>
                    <z>12</z>
                </domain>
                <r_cutoff>2.75</r_cutoff>
                <boundary>
                    <x_high>
                        <Outflow/>
                    </x_high>
                    <x_low>
                        <Outflow/>
                    </x_low>
                    <y_high>
                        <Periodic/>
                    </y_high>
                    <y_low>
                        <Periodic/>
                    </y_low>
                    <z_high>
                        <Periodic/>
                    </z_high>
                    <z_low>
                        <Periodic/>
                    </z_low>
                </boundary>
            </linkedCells>
        </container>
        <force>
            <LennardJones/>
            <SingularGravity g="-0.8"/>
        </force>
        <delta_t>0.0005</delta_t>
        <t_end>10</t_end>
        <twoD>false</twoD>
        <statistics>
            <x_bins>50</x_bins>
            <y_bins>1</y_bins>
            <output_interval>10000</output_interval>
        </statistics>
    </metadata>
    <cuboids>
        <cuboid>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <corner>
                <x>1.0</x>
                <y>0.5</y>
                <z>0.5</z>
            </corner>
            <dimensions>
                <x>2</x>
                <y>30</y>
                <z>12</z>
            </dimensions>
            <type>-1</type>
            <h>1.0</h>
            <mass>1.0</mass>
            <epsilon>2.0</epsilon>
            <sigma>1.1</sigma>
            <mv>0.0</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>27.2</x>
                <y>0.5</y>
                <z>0.5</z>
            </corner>
            <dimensions>
                <x>2</x>
                <y>30</y>
                <z>12</z>
            </dimensions>
            <type>-2</type>
            <h>1.0</h>
            <mass>1.0</mass>
            <epsilon>2.0</epsilon>
            <sigma>1.1</sigma>
            <mv>0.0</mv>
        </cuboid>
        <cuboid>
            <velocity>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </velocity>
            <corner>
                <x>3.2</x>
                <y>0.6</y>
                <z>0.6</z>
            </corner>
            <dimensions>
                <x>20</x>
                <y>25</y>
                <z>10</z>
            </dimensions>
            <type>1</type>
            <h>1.2</h>
            <mass>1.0</mass>
            <epsilon>1.0</epsilon>
            <sigma>1.0</sigma>
            <mv>0.0</mv>
        </cuboid>
    </cuboids>
    <thermostat>
        <T_init>40</T_init>
        <n_thermostat>10</n_thermostat>
        <use_thermal_motion>true</use_thermal_motion>
    </thermostat>
</simulation>
